//plugins {
//    id("com.android.application")
//    id("org.jetbrains.kotlin.android")
//    id("com.google.android.libraries.mapsplatform.secrets-gradle-plugin")
//}
apply plugin: 'com.android.application'

// v-- START OF THE CUSTOM CODE --v

// 1. Create a Properties object to hold the values
def localProperties = new Properties()

// 2. Create a reference to the local.properties file in the root project
def localPropertiesFile = rootProject.file('local.properties')

// 3. Load the properties file if it exists
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
}

// ^-- END OF THE CUSTOM CODE --^

repositories {
    google()
}

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    defaultConfig {
        applicationId "com.assistant.main"
        //minSdkVersion 21
        minSdkVersion 24
        targetSdkVersion 29
        versionCode 2
        versionName "2.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // v-- USE buildConfigField TO ADD THE VALUES --v

        // Use the loaded properties to create BuildConfig fields.
        // Provide a default value "" if the key is not found.
        buildConfigField "String", "SMARTLIFE_USER", "${localProperties.getProperty('SMARTLIFE_USER', '')}"
        buildConfigField "String", "SMARTLIFE_PWD", "${localProperties.getProperty('SMARTLIFE_PWD', '')}"
        buildConfigField "String", "SMARTLIFE_REGION", "${localProperties.getProperty('SMARTLIFE_REGION', '')}"

        // ^-- END OF THE buildConfigField SECTION --^
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':aars')
    implementation project(':models')
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation project(path: ':porcupine')
    implementation project(path: ':porcupinemanager')
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
    implementation 'com.koushikdutta.async:androidasync:2.2.1'
    implementation fileTree(dir: 'libs', include: ['*.aar', '*.jar'], exclude: [])
    implementation 'com.google.mediapipe:tasks-genai:0.10.14'
    implementation 'commons-io:commons-io:2.4'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.google.code.gson:gson:2.10.1'

}

